AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app
  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      Policies:
        DynamoDBCrudPolicy:
          TableName: !Ref DynamoDBTable
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
        Health:
          Type: Api
          Properties:
            Path: /health
            Method: get
        GetProduct:
          Type: Api
          Properties:
            Path: /product
            Method: get
        CreateProduct:
          Type: Api
          Properties:
            Path: /product
            Method: post
        UpdateProduct:
          Type: Api
          Properties:
            Path: /product
            Method: patch
        DeleteProduct:
          Type: Api
          Properties:
            Path: /product
            Method: delete
        getProducts:
          Type: Api
          Properties:
            Path: /products
            Method: get

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    # Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: paper-trader-transactions
      AttributeDefinitions:
        - 
          AttributeName: productId
          AttributeType: S
      #   BillingMode: PAY_PER_REQUEST
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      KeySchema: 
        -
          AttributeName: productId
          KeyType: HASH



Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
